### ISSUE TITLE
404 on hebcal.com/i/adobehebrew-bold.woff2

### ISSUE THREAD

**Issue by haimn** [hebcal/hebcal-web#23]
I get 404 for the "adobehebrew-bold" font in fridge candle light Hebrew page (for example: [this page](https://www.hebcal.com/shabbat/fridge.cgi?geonameid=281184&b=40&M=on&lg=he-x-NoNikud&year=5782)).
I can't open pull request for [fridge.ejs](https://github.com/hebcal/hebcal-web/blob/40ed7bc07212388d2a6fb7a24d6ea940e6db3b4b/views/fridge.ejs) as I don't know where the actual adobehebrew-bold is.

**Comment by mjradwin** [comment]
Thanks for the bug report! The missing file has been deployed and this is now fixed.
