### ISSUE TITLE
Converter API in XML doesn't have the same fields as JSON

### ISSUE THREAD

**Issue by 99littlebugs** [hebcal/hebcal-web#33]
Longtime fan of hebcal here - thank you! 

I'm following [these instructions](https://www.hebcal.com/home/219/hebrew-date-converter-rest-api) and I noticed that the `heDateParts` field doesn't exist in the XML response. I'm interested in using XML as I am building an excel integration and XML parsing comes free. 

Alternatively, I would like to be able to control the "language" of the str field in the XML so that it doesn't have nekudot and the preceding ב (same as the toggle you have on the [website](https://www.hebcal.com/converter?hd=12&hm=Elul&hy=5774&h2g=1) - "show hebrew nekudot")

Is this currently possible?

**Comment by mjradwin** [comment]
Thank you for the suggestion. You can specify &lg=he-x-NoNikud if you want
event titles in Hebrew without nikud.

We will keep this issue open as an enhancement request to add the
heDateParts to XML format.

**Comment by 99littlebugs** [comment]
Thank you. Another question, for the hebrew to gregorian (#3 in those docs) `https://www.hebcal.com/converter?cfg=json&hy=5749&hm=Kislev&hd=25&h2g=1&strict=1` is there a way to specify that the hebrew date is post sunset?

**Comment by mjradwin** [comment]
Yes, as described on the documentation, &gs=on for after sunset. (Default &gs=off for before sunset)

**Comment by mjradwin** [comment]
to clarify previous comment: the `gs` parameter is only used for Gregorian to Hebrew conversion. There is no way to specify after sunset when converting from Hebrew to Gregorian. If `gs` is specified on `h2g=1` it will be ignored.

**Comment by 99littlebugs** [comment]
Right, I think really what I'm getting at is wondering if there is a "before midnight" flag when doing hebrew to gregorian conversion?

**Comment by mjradwin** [comment]
There isn't. When you convert from Hebrew to Gregorian, you'll get the Gregorian date that corresponds to the majority of that Hebrew date. If your application needs to know the Erev, just subtract one day from the Gregorian date using whatever native date library your application uses

**Comment by 99littlebugs** [comment]
Thanks for the confirmation

**Comment by mjradwin** [comment]
> Thank you for the suggestion. We will keep this issue open as an enhancement request to add the heDateParts to XML format.

OK, we've added the Hebrew date parts in gematriya to XML. The response includes a new `hebdate` element which is a sibling of the `hebrew` element.

For example:

https://www.hebcal.com/converter?cfg=xml&gd=24&gm=9&gy=2024&gs=on&g2h=1&strict=1

Produces:

```xml
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<hebcal>
<gregorian year="2024" month="9" day="24"/>
<hebrew year="5784" month="Elul" day="22" str="כ״ב בֶּאֱלוּל תשפ״ד"/>
<hebdate year="תשפ״ד" month="אלול" day="כ״ב"/>
<events>
<event name="Parashat Nitzavim-Vayeilech" diaspora="1" israel="1" href="https://www.hebcal.com/sedrot/nitzavim-vayeilech-20240928"/>
</events>
</hebcal>
```
